### PR TITLE
Replace the update ETAs example with an example to update RSAs

### PR DESCRIPTION
**Pull request by Raibaz**
Since ETAs are now deprecated and RSAs are the suggested replacement.

### CODE REVIEW

**Review by jradcliff — APPROVED** [review]
Is the plan to add this example and also update https://developers.google.com/google-ads/api/docs/ads/mutate-ads?

Thanks

**Review by sundquist — APPROVED** [review]
LGTM

**Comment by Raibaz** [comment]
> Is the plan to add this example and also update https://developers.google.com/google-ads/api/docs/ads/mutate-ads?

Sure, I'll update the docs once this is merged.

**Comment by jradcliff** [comment]
Sounds good. Thanks for updating the docs.

**Pull request merged**
